// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.error(
    '[Supabase] Missing environment variables. Copy .env.example to .env and set ' +
    'VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (find them in your ' +
    'Supabase project settings), then restart the dev server.'
  );
}

const resolvedUrl = SUPABASE_URL || 'https://placeholder.supabase.co';
const resolvedKey = SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

/**
 * Custom fetch wrapper for Supabase that:
 * 1. Adds the `apikey` header for new-style Supabase API keys (sb_publishable_ / sb_secret_)
 * 2. Strips duplicate Authorization header when the key style has changed
 */
function createSupabaseFetch(supabaseKey: string): typeof fetch {
  const isNewKey = supabaseKey.startsWith('sb_publishable_') || supabaseKey.startsWith('sb_secret_');
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );
    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }
    // New-style keys don't use Bearer token auth — just pass apikey
    if (isNewKey) {
      if (headers.get('Authorization')) {
        headers.delete('Authorization');
      }
      headers.set('apikey', supabaseKey);
    }
    return fetch(input, { ...init, headers });
  };
}

export const supabase = createClient<Database>(resolvedUrl, resolvedKey, {
  global: {
    fetch: createSupabaseFetch(resolvedKey),
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'pkce',
  }
});
